// User mode type
export type UserMode = "normal" | "advanced";

// Database types
export interface User {
  id: number;
  telegram_id: number;
  mode: UserMode;
  created_at: string;
}

// Keyword embedding for semantic matching
export interface KeywordEmbedding {
  keyword: string;
  vec: number[];
}

// Embeddings for all keywords in a subscription
export interface KeywordEmbeddings {
  pos: KeywordEmbedding[];
  neg: KeywordEmbedding[];
}

export interface Subscription {
  id: number;
  user_id: number;
  original_query: string;
  positive_keywords: string[]; // stored as JSON in DB
  negative_keywords: string[]; // stored as JSON in DB
  disabled_negative_keywords?: string[]; // stored as JSON in DB, for toggle feature
  llm_description: string;
  keyword_embeddings?: KeywordEmbeddings; // stored as JSON in DB, for BGE-M3 semantic matching
  is_active: number; // SQLite boolean
  created_at: string;
}

export interface MonitoredGroup {
  id: number;
  telegram_id: number;
  title: string | null;
  added_at: string;
}

export interface MatchedMessage {
  id: number;
  subscription_id: number;
  message_id: number;
  group_id: number;
  matched_at: string;
}

// Matcher types
export interface MatchResult {
  subscription: Subscription;
  score: number;
  stage: "bm25" | "ngram" | "llm" | "query_fallback";
  passed: boolean;
}

export interface KeywordGenerationResult {
  positive_keywords: string[];
  negative_keywords: string[];
  llm_description: string;
}

// Pending group during selection flow
export interface PendingGroup {
  id: number;
  title?: string;
  username?: string;
  needsInviteLink: boolean;
  inviteLink?: string;
  isChannel: boolean;
}

// Rating type for example messages
export type ExampleRating = "hot" | "warm" | "cold";

// Example message for rating
export interface RatingExample {
  id: number;
  text: string;
  groupId: number;
  groupTitle: string;
  isGenerated: boolean; // true if generated by LLM (no real messages found)
}

// Media item from message (photo or video)
export interface MediaItem {
  type: "photo" | "video";
  buffer: Uint8Array;
  width?: number;
  height?: number;
  duration?: number; // for video
  mimeType: string;
}

// Stored media reference in DB
export interface StoredMedia {
  id: number;
  message_id: number;
  group_id: number;
  media_index: number;
  media_type: "photo" | "video";
  file_path: string;
  width: number | null;
  height: number | null;
  duration: number | null;
  created_at: string;
}

// Message from monitored group
export interface IncomingMessage {
  id: number;
  group_id: number;
  group_title: string;
  text: string;
  sender_name: string;
  sender_username?: string;
  timestamp: Date;
  media?: MediaItem[];
}

// WebApp types
export interface Category {
  id: number;
  code: string;
  name_ru: string;
  created_at: string;
}

export interface Product {
  id: number;
  message_id: number;
  group_id: number;
  group_title: string;
  text: string;
  category_code: string | null;
  price_raw: string | null;
  price_normalized: number | null;
  sender_id: number | null;
  sender_name: string | null;
  message_date: number;
  classified_at: string;
}

export interface SellerContact {
  id: number;
  product_id: number;
  contact_type: string;
  contact_value: string;
  source: string;
  created_at: string;
}

// Persistent message storage (replaces in-memory cache)
export interface StoredMessage {
  id: number;
  message_id: number;
  group_id: number;
  group_title: string | null;
  topic_id: number | null;
  topic_title: string | null;
  text: string;
  sender_id: number | null;
  sender_name: string | null;
  sender_username: string | null;
  timestamp: number;
  is_deleted: number;
  created_at: string;
  updated_at: string;
}

// Topic for forum groups
export interface Topic {
  id: number;
  group_id: number;
  topic_id: number;
  title: string | null;
  updated_at: string;
}
