// User mode type
export type UserMode = "normal" | "advanced";

// Database types
export interface User {
  id: number;
  telegram_id: number;
  mode: UserMode;
  created_at: string;
}

// Keyword embedding for semantic matching
export interface KeywordEmbedding {
  keyword: string;
  vec: number[];
}

// Embeddings for all keywords in a subscription
export interface KeywordEmbeddings {
  pos: KeywordEmbedding[];
  neg: KeywordEmbedding[];
}

export interface Subscription {
  id: number;
  user_id: number;
  original_query: string;
  positive_keywords: string[]; // stored as JSON in DB
  negative_keywords: string[]; // stored as JSON in DB
  disabled_negative_keywords?: string[]; // stored as JSON in DB, for toggle feature
  llm_description: string;
  keyword_embeddings?: KeywordEmbeddings; // stored as JSON in DB, for BGE-M3 semantic matching
  is_active: number; // SQLite boolean
  created_at: string;
}

export interface MonitoredGroup {
  id: number;
  telegram_id: number;
  title: string | null;
  added_at: string;
}

export interface MatchedMessage {
  id: number;
  subscription_id: number;
  message_id: number;
  group_id: number;
  matched_at: string;
}

// Matcher types
export interface MatchResult {
  subscription: Subscription;
  score: number;
  stage: "bm25" | "ngram" | "llm";
  passed: boolean;
}

export interface KeywordGenerationResult {
  positive_keywords: string[];
  negative_keywords: string[];
  llm_description: string;
}

// Pending group during selection flow
export interface PendingGroup {
  id: number;
  title?: string;
  username?: string;
  needsInviteLink: boolean;
  inviteLink?: string;
  isChannel: boolean;
}

// Rating type for example messages
export type ExampleRating = "hot" | "warm" | "cold";

// Example message for rating
export interface RatingExample {
  id: number;
  text: string;
  groupId: number;
  groupTitle: string;
  isGenerated: boolean; // true if generated by LLM (no real messages found)
}

// Bot state for conversation flow
export interface UserState {
  step:
    | "idle"
    | "clarifying_query"
    | "rating_examples" // new: rating similar messages
    | "awaiting_confirmation"
    | "editing_keywords"
    | "selecting_groups"
    | "adding_group"
    | "awaiting_invite_link"
    // States for editing existing subscriptions
    | "editing_sub_positive"
    | "editing_sub_negative"
    | "editing_sub_description"
    | "editing_sub_ai"
    // States for add/remove keywords flow
    | "adding_positive"
    | "adding_negative"
    | "removing_positive"
    | "removing_negative";
  // Clarification flow data
  clarification?: {
    original_query: string;
    questions: string[];
    answers: string[];
    current_index: number;
  };
  pending_subscription?: {
    original_query: string;
    positive_keywords: string[];
    negative_keywords: string[];
    llm_description: string;
  };
  pending_groups?: PendingGroup[];
  current_pending_group?: PendingGroup; // group awaiting invite link
  selected_groups?: { id: number; title: string }[];
  available_groups?: { id: number; title: string }[];
  // ID of subscription being edited
  editing_subscription_id?: number;
  // AI editing flow data
  pending_ai_edit?: {
    subscription_id: number;
    current: {
      positive_keywords: string[];
      negative_keywords: string[];
      llm_description: string;
    };
    proposed?: {
      positive_keywords: string[];
      negative_keywords: string[];
      llm_description: string;
    };
    conversation: Array<{ role: "user" | "assistant"; content: string }>;
  };
  // Rating examples flow data
  pending_examples?: {
    messages: RatingExample[];
    ratings: Array<{
      messageId: number;
      text: string;
      rating: ExampleRating;
    }>;
    current_index: number;
  };
  // Draft keywords for searching similar messages
  draft_keywords?: string[];
}

// Message from monitored group
export interface IncomingMessage {
  id: number;
  group_id: number;
  group_title: string;
  text: string;
  sender_name: string;
  timestamp: Date;
}

// WebApp types
export interface Category {
  id: number;
  code: string;
  name_ru: string;
  created_at: string;
}

export interface Product {
  id: number;
  message_id: number;
  group_id: number;
  group_title: string;
  text: string;
  category_code: string | null;
  price_raw: string | null;
  price_normalized: number | null;
  sender_id: number | null;
  sender_name: string | null;
  message_date: number;
  classified_at: string;
}

export interface SellerContact {
  id: number;
  product_id: number;
  contact_type: string;
  contact_value: string;
  source: string;
  created_at: string;
}

// Persistent message storage (replaces in-memory cache)
export interface StoredMessage {
  id: number;
  message_id: number;
  group_id: number;
  group_title: string | null;
  topic_id: number | null;
  topic_title: string | null;
  text: string;
  sender_id: number | null;
  sender_name: string | null;
  timestamp: number;
  is_deleted: number;
  created_at: string;
  updated_at: string;
}

// Topic for forum groups
export interface Topic {
  id: number;
  group_id: number;
  topic_id: number;
  title: string | null;
  updated_at: string;
}
